import type { LlmConfig, LlmProvider } from '#/config/llmConfig.js';
import { getHubModelById } from '#/server/llm/models.js';

const OPENAI_BASE_URL = 'https://api.openai.com/v1';
const CLAUDE_BASE_URL = 'https://api.anthropic.com/v1';
const GEMINI_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/openai';

/**
 * Serializable tool call returned from a provider completion.
 */
export interface LlmToolCall {
  /**
   * Tool call id from the model.
   */
  id: string;

  /**
   * Tool function name.
   */
  name: string;

  /**
   * JSON-encoded tool arguments.
   */
  arguments: string;
}

/**
 * Token usage reported by the provider for one completion.
 */
export interface LlmCompletionUsage {
  /**
   * Prompt tokens consumed by the request.
   */
  promptTokens: number;

  /**
   * Completion tokens generated by the model.
   */
  completionTokens: number;

  /**
   * Total tokens billed for the request.
   */
  totalTokens: number;
}

/**
 * Normalized result of one OpenAI-compatible chat completion.
 */
export interface LlmCompletionResult {
  /**
   * Assistant text when the model finishes without tool calls.
   */
  content: string | null;

  /**
   * Tool calls requested by the assistant, when present.
   */
  toolCalls?: LlmToolCall[];

  /**
   * Token usage for metering.
   */
  usage: LlmCompletionUsage;
}

/**
 * Message role accepted by the OpenAI-compatible chat API.
 */
export type LlmChatMessageRole = 'system' | 'user' | 'assistant' | 'tool';

/**
 * Serializable chat message for provider requests.
 */
export interface LlmChatMessage {
  /**
   * OpenAI-compatible message role.
   */
  role: LlmChatMessageRole;

  /**
   * Text content for the message.
   */
  content?: string | null;

  /**
   * Tool calls on assistant messages.
   */
  tool_calls?: LlmToolCall[];

  /**
   * Tool call id for tool role messages.
   */
  tool_call_id?: string;

  /**
   * Optional tool name for tool role messages.
   */
  name?: string;
}

/**
 * OpenAI-compatible tool definition passed through from the client.
 */
export type LlmToolDefinition = Record<string, unknown>;

/**
 * Input for one hub-proxied chat completion.
 */
export interface RunLlmCompletionInput {
  /**
   * Provider-specific model id.
   */
  model: string;

  /**
   * Conversation messages excluding the system prompt.
   */
  messages: LlmChatMessage[];

  /**
   * Optional system prompt injected ahead of messages.
   */
  systemPrompt?: string;

  /**
   * Optional tool definitions forwarded to the provider.
   */
  tools?: LlmToolDefinition[];
}

/**
 * Resolves the base URL for an OpenAI-compatible provider.
 *
 * @param provider - LLM provider to call.
 */
function resolveProviderBaseUrl(provider: LlmProvider): string {
  switch (provider) {
    case 'openai':
      return OPENAI_BASE_URL;
    case 'claude':
      return CLAUDE_BASE_URL;
    case 'gemini':
      return GEMINI_BASE_URL;
    default: {
      const exhaustive: never = provider;
      return exhaustive;
    }
  }
}

/**
 * Maps hub messages into OpenAI-compatible request message objects.
 *
 * @param messages - Messages from the client step request.
 */
function toProviderMessages(messages: LlmChatMessage[]): Record<string, unknown>[] {
  return messages.map((message) => {
    if (message.role === 'assistant' && message.tool_calls?.length) {
      return {
        role: 'assistant',
        content: message.content ?? null,
        tool_calls: message.tool_calls.map((call) => ({
          id: call.id,
          type: 'function',
          function: {
            name: call.name,
            arguments: call.arguments
          }
        }))
      };
    }

    if (message.role === 'tool') {
      return {
        role: 'tool',
        tool_call_id: message.tool_call_id ?? '',
        content: message.content ?? ''
      };
    }

    return {
      role: message.role,
      content: message.content ?? ''
    };
  });
}

/**
 * Parses provider usage fields into normalized token counts.
 *
 * @param usage - Raw usage object from the provider response.
 */
function parseUsage(usage: Record<string, unknown> | undefined): LlmCompletionUsage {
  const promptTokens = typeof usage?.prompt_tokens === 'number' ? usage.prompt_tokens : 0;
  const completionTokens =
    typeof usage?.completion_tokens === 'number' ? usage.completion_tokens : 0;
  const totalTokens =
    typeof usage?.total_tokens === 'number' ? usage.total_tokens : promptTokens + completionTokens;

  return {
    promptTokens,
    completionTokens,
    totalTokens
  };
}

/**
 * Parses an OpenAI-compatible chat completion response body.
 *
 * @param json - Parsed JSON response body.
 */
function parseCompletionResponse(json: Record<string, unknown>): LlmCompletionResult {
  const choices = json.choices;
  if (!Array.isArray(choices) || choices.length === 0) {
    throw new Error('The model returned an empty response.');
  }

  const message = choices[0]?.message as Record<string, unknown> | undefined;
  if (!message) {
    throw new Error('The model returned an empty response.');
  }

  const rawToolCalls = message.tool_calls;
  const toolCalls = Array.isArray(rawToolCalls)
    ? rawToolCalls
      .filter((call): call is Record<string, unknown> => call != null && typeof call === 'object')
      .filter((call) => call.type === 'function')
      .map((call) => {
        const fn = call.function as Record<string, unknown> | undefined;
        return {
          id: String(call.id ?? ''),
          name: String(fn?.name ?? ''),
          arguments: String(fn?.arguments ?? '')
        };
      })
      .filter((call) => call.id && call.name)
    : undefined;

  const content = typeof message.content === 'string' ? message.content : null;

  return {
    content,
    ...(toolCalls && toolCalls.length > 0 ? { toolCalls } : {}),
    usage: parseUsage(json.usage as Record<string, unknown> | undefined)
  };
}

/**
 * Runs one OpenAI-compatible chat completion against a configured provider.
 *
 * @param config - Hub LLM configuration with provider API keys.
 * @param input - Model, messages, optional system prompt, and tools.
 * @returns Normalized assistant content, tool calls, and usage.
 */
export async function runLlmCompletion(
  config: LlmConfig,
  input: RunLlmCompletionInput
): Promise<LlmCompletionResult> {
  const modelEntry = getHubModelById(input.model);
  if (!modelEntry) {
    throw new Error(`Unknown model: ${input.model}`);
  }

  const providerConfig = config.providers[modelEntry.provider];
  if (!providerConfig?.apiKey.trim()) {
    throw new Error(`Provider ${modelEntry.provider} is not configured on this hub.`);
  }

  const messages: Record<string, unknown>[] = [];
  if (input.systemPrompt?.trim()) {
    messages.push({ role: 'system', content: input.systemPrompt });
  }
  messages.push(...toProviderMessages(input.messages));

  const body: Record<string, unknown> = {
    model: modelEntry.id,
    messages
  };

  if (input.tools && input.tools.length > 0) {
    body.tools = input.tools;
  }

  const response = await fetch(`${resolveProviderBaseUrl(modelEntry.provider)}/chat/completions`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${providerConfig.apiKey}`,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      errorText.trim() || `LLM request failed with status ${response.status.toString()}`
    );
  }

  const json = (await response.json()) as Record<string, unknown>;
  return parseCompletionResponse(json);
}
